- hosts: lab-win
  tasks:
    - name: Disable feature update #1
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        name: DisableOSUpgrade
        data: 1
        type: dword

    - name: Disable feature update #2
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\OSUpgrade
        name: AllowOSUpgrade
        data: 0
        type: dword

    - name: Enable Remote Desktop
      win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword

    - name: Disable Windows Firewall
      win_firewall:
        state: disabled
        profiles:
        - Domain
        - Private
        - Public
      tags: disable_firewall

    - name: Disable Hibernation
      win_command: powercfg.exe -h off
    


