- hosts: windows 
  gather_facts: no
  tasks:
    - name: Disable feature update #1
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        name: DisableOSUpgrade
        data: 1
        type: dword

    - name: Disable feature update #2
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\OSUpgrade
        name: AllowOSUpgrade
        data: 0
        type: dword

    - name: Enable Remote Desktop
      win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword

    - name: Disable Sleep AC
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\abfc2519-3608-4c2a-94ea-171b0ed546ab
        name: ACSettingIndex
        data: 0
        type: dword

    - name: Disable Sleep DC
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\abfc2519-3608-4c2a-94ea-171b0ed546ab
        name: DCSettingIndex
        data: 0
        type: dword

    - name: Disable Windows Firewall
      win_firewall:
        state: disabled
        profiles:
        - Domain
        - Private
        - Public
      tags: disable_firewall

    - name: Disable Hibernation
      win_command: powercfg.exe -h off

    - name: Ensure the required NuGet package provider version is installed
      ansible.windows.win_shell: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      tags:
      - sysmon
      - syslog

    - name: Install-Module Pscx (required for unzip)
      community.windows.win_psmodule:
        name: pscx
        state: present
        allow_clobber: yes
      tags:
      - sysmon
      - syslog

    - name: Download sysmon config
      ansible.windows.win_get_url:
        url: https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml
        dest: C:\Windows\Temp\sysmonconfig-export.xml
      tags:
      - sysmon
      - syslog
    
    - name: Download sysmon.zip
      ansible.windows.win_get_url:
        url: https://download.sysinternals.com/files/Sysmon.zip
        dest: C:\Windows\Temp\Sysmon.zip
      tags:
      - sysmon
      - syslog

    - name: Extract Sysmon
      community.windows.win_unzip:
        src: C:\Windows\Temp\Sysmon.zip
        dest: C:\Windows\Temp
        recurse: yes
      tags:
      - sysmon
      - syslog

    - name: Install Sysmon
      ansible.windows.win_package:
        path: C:\Windows\Temp\Sysmon64.exe
        arguments: '-i C:\Windows\Temp\sysmonconfig-export.xml -accepteula'
        state: present
      tags:
      - sysmon
      - syslog
      
    - name: Download nxlog
      ansible.windows.win_get_url:
        url: https://nxlog.co/system/files/products/files/348/nxlog-ce-2.10.2150.msi
        dest: C:\Windows\Temp\nxlog-ce-2.10.2150.msi
      tags:
      - sysmon
      - syslog

    - name: Install nxlog
      ansible.windows.win_package:
        path: C:\Windows\Temp\nxlog-ce-2.10.2150.msi
        state: present
      tags:
      - sysmon
      - syslog
    
    - name: Update nxlog.conf
      lineinfile:
        path: C:\Program Files (x86)\nxlog\conf\nxlog.conf
        insertafter: EOF
        line: test
      tags: 
      - sysmon
      - syslog
      - test

    - name: Restart nxlog service
      ansible.windows.win_service:
        name: nxlog
        state: restarted
      tags:
      - sysmon
      - syslog

    - name: Change the hostname
      win_hostname:
        name: "{{ inventory_hostname }}"
      register: winhostname
    
    - name: Reboot {{ inventory_hostname }}
      win_reboot:
      when: winhostname.reboot_required
    


